FROM ruby:3.2.3-slim

WORKDIR /rails
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libvips sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV=development BUNDLE_WITHOUT="test" BUNDLE_PATH="/usr/local/bundle"

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .
EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
